In [ ]:
import argparse

parser = argparse.ArgumentParser("Hyperparameters Setting for MADDPG and MATD3 in MPE environment")
parser.add_argument("--algorithm", type=str, default="MATD3", help="MADDPG or MATD3")
parser.add_argument("--buffer_size", type=int, default=int(1e6), help="The capacity of the replay buffer")

args = parser.parse_args()
print(args.algorithm)

list加法

In [1]:
l1 = [1, 2, 3]
l2 = [4, 5, 6]
l3 = l1 + l2
print(l3)

[1, 2, 3, 4, 5, 6]


In [3]:
import numpy as np


n1 = np.array([1, 2, 3])
n2 = np.array([4, 5, 6])
n3 = l1 + l2
n0 = np.zeros(3)
print(n3)
print(n0)

[5 7 9]
[0. 0. 0.]


list.append(list)

In [3]:
import torch


l1 = []
l2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
t1 = torch.tensor(l2, dtype=torch.float32)
l1.append(t1)
actor_inputs = torch.cat([x for x in l1], dim=-1)
print(l1)
print(actor_inputs)

[tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])]
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
